version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        user: developer
        uid: 1000
    container_name: cashpilot_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8002:80"
    depends_on:
      - rabbitmq
    networks:
      - cash-pilot-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cashpilot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - cash-pilot-network

networks:
  cash-pilot-network:
    driver: bridge
